### ISSUE TITLE
MultiValueDictKeyError at /uploads/simple/ error

### ISSUE THREAD

**Issue by taohuadaohongye** [MahsaSeifikar/tweetphus#1]
when i upload the .pickle file . it show "File uploaded at: /media/.pickle_GkLLLMQ"
but when i click crawl ,it show:
MultiValueDictKeyError at /uploads/simple/
'myfile'

**Comment by MahsaSeifikar** [comment]
First, you should choose your file, then click on crawl button. You cannot use the file you upload to the system for the crawling option. I'm working on this project to add better features.
